version: '3'

networks:
  dockerapi-dev:
    driver: bridge

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "divisima"
      POSTGRES_PASSWORD: "divisima"
      POSTGRES_DB: "divisima"
    networks:
      - dockerapi-dev  
