version: '3'

networks:
  dockerapi-dev:
    driver: bridge

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: "divisima"
      POSTGRES_PASSWORD: "divisima"
      POSTGRES_DB: "divisima"
    networks:
      - dockerapi-dev  

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
#    volumes:
#      - $PWD/redis-data:/var/lib/redis
#          - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master